---
title: "Legiplot modifications"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Modification actuelles

```{r modif.data}
lp_stats_lts0 <- read.csv("stats_shortlist_lts0.csv",encoding = "UTF-8", stringsAsFactors = TRUE) %>%
    mutate(code = factor(code, labels=str_replace_all(levels(code),'_',' '))) %>%
  select(-date)

lp_diff_shortlist_t <- read.csv("diff_shortlist_t.csv",encoding = "UTF-8", stringsAsFactors = TRUE) %>%
    mutate(code = factor(code, labels=str_replace_all(levels(code),'_',' '))) %>%
    mutate(
      année = as.factor(substr(date,1,4)),
      date = as.Date(date)
      )

lp_actu <- full_join(
  lp_stats_lts0,
  lp_diff_shortlist_t %>% 
    filter(date > as.Date("2011-05-14")) %>% 
    select(date,code,article,type)
) %>%
  mutate(type = fct_explicit_na(type,"Conservation")) %>%
  group_by(code,partie,article,type) %>%
  summarise(nb = n()) %>%
  pivot_wider(names_from = type, values_from = nb, values_fill = 0) %>%
  mutate(type=factor(case_when(
    Modification > 0 ~ "Modification",
    Ajout > 0 & Suppression > 0 ~ "Modification",
    Ajout > 0 ~ "Ajout",
    Suppression > 0 ~ "Suppression",
    TRUE ~ "Conservation"),
    levels=c("Conservation","Modification","Ajout","Suppression")
  ))
```

```{r modif.plot}
lp_actu %>%
  mutate(partie = ifelse(str_detect(partie,"législative")|is.na(partie),"législative","autre")) %>%
  group_by(code,type) %>%
  summarise(nb_articles = n()) %>% 
  ggplot(aes(x=code,y=nb_articles,fill=type)) +
  geom_col(position = "fill") +
  #facet_grid(.~partie)+
  coord_flip()
```

### Modifications dans le temps


```{r modif.data}
lp_stats_ts6 <- read.csv("stats_shortlist_ts6.csv",encoding = "UTF-8", stringsAsFactors = TRUE) %>%
  mutate(code = factor(code, labels=str_replace_all(levels(code),'_',' '))) %>%
  mutate(date = as.Date(date))

lp_diff_ts6 <- read.csv("diff_shortlist_t.csv",encoding = "UTF-8", stringsAsFactors = TRUE) %>%
  mutate(code = factor(code, labels=str_replace_all(levels(code),'_',' '))) %>%
  mutate(date = as.Date(date)) %>%
  group_by(code,date,type) %>%
  summarise(nb = n()) %>%
  pivot_wider(names_from = type, values_from = nb, values_fill = 0) 

lp_diff_date <- full_join(lp_stats_ts6,lp_diff_ts6) %>%
  mutate(Année = format(date, "%Y")) %>%
  mutate(
    Conservation = nb_articles - Ajout - Suppression - Modification
  )

lp_diff_year <- lp_diff_date %>%
  group_by(code,Année) %>%
  arrange(Année) %>%
  summarise(
    nb_articles = last(nb_articles),
    Ajout = sum(Ajout),
    Suppression = sum(Suppression),
    Modification = sum(Modification)
  ) %>%
  mutate(
    Taux.modification = Modification / nb_articles,
    Conservation = nb_articles - Ajout - Suppression - Modification)
```

```{r modif.date.plot}
lp_diff_year %>%
  filter(Année >= "2000") %>%
  ggplot(aes(x=Année,y=Taux.modification,color=code)) +
  geom_line(aes(group=code))

```



### Modifications dans le temps 2


```{r modif.data}
library(tidyverse)
lp_modifs <- read.csv("diff_shortlist_t.csv",encoding = "UTF-8", stringsAsFactors = TRUE) %>%
  mutate(code = factor(code, labels=str_replace_all(levels(code),'_',' '))) %>%
  mutate(date = as.Date(date)) %>%
  mutate(mandature = case_when(
    date < as.Date("2007-05-15") ~ "Chirac",
    date < as.Date("2012-05-15") ~ "Sarkozy",
    date < as.Date("2017-05-15") ~ "Hollande",
    TRUE ~ "Macron"
  ))


lp_modifs2 <- lp_modifs %>%
  filter(code == "code de l'éducation") %>%
  mutate(année = as.factor(format(date, "%Y"))) %>%
  group_by(code, mandature, article, type) %>%
  summarise(nb = n()) %>%
  pivot_wider(names_from = type, values_from = nb, values_fill = 0 ) %>%
  complete(code,mandature,article)

lp_modifs2 <- lp_modifs %>%
  mutate(
    AjSuppr = cumsum(case_when(
      type == "Ajout" ~ 1,
      type == "Préexistence" ~ 1,
      type == "Suppression" ~ -1,
      TRUE ~ 0)),
    Modifications = cumsum(ifelse(is.na(type),0,1))
    )
  

```

```{r modif.date.plot}
lp_diff_year %>%
  filter(Année >= "2000") %>%
  ggplot(aes(x=Année,y=Taux.modification,color=code)) +
  geom_line(aes(group=code))

```